name: Docker Image CI

on:
  push:
    branches: [ "develop", "automated"]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Get Descriptions for tags
      id: describe
      run: |
        echo "::set-output name=date::$(date +'%Y-%m-%d')"
        echo "::set-output name=git-describe::$(git describe --always)"

    # Build choosenim image
    - uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64
        file: choosenim/Dockerfile
        push: true
        tags: |
          ekajake/choosenim-test:latest
    # Build Nim images
    - uses: jiro4989/setup-nim-action@v2
      with:
        nim-version: '2.0.0' # default is 'stable'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - run: nim r build.nim
